## Numpy Array Operations

In [3]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: ", arr[2:7])
print("With Steps: ",arr[2:7:2])
print("Positive indexing: ",arr[3])
print("Negative indexing: ",arr[-3])

Basic slicing:  [3 4 5 6 7]
With Steps:  [3 5 7]
Positive indexing:  4
Negative indexing:  8


In [29]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specifi element: ",arr_2d[2,1])
print("Entire row: ",arr_2d[2])
print("Entire column: ",arr_2d[:,2])

Specifi element:  8
Entire row:  [7 8 9]
Entire column:  [3 6 9]


## Sorting

In [30]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted array: ",np.sort(unsorted))

arr_2d_unsorred = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array by row: ",np.sort(arr_2d_unsorred))
print("Sorted 2D array by column: ",np.sort(arr_2d_unsorred, axis=0))
print("Sorted 2D array by column: ",np.sort(arr_2d_unsorred, axis=1))



Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by row:  [[1 3]
 [1 2]
 [2 3]]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by column:  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [31]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2==0]
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [32]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [35]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("NP where: ",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [46]:
print(numbers[5])
print(numbers[numbers>5])
print(numbers)
condition_array = np.where(numbers>=5, numbers*4, numbers)
print(condition_array)

6
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4 20 24 28 32 36 40]


## Adding and removing data

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combine = arr1 + arr2
combine = np.concatenate((arr1,arr2))
print(combine)

NameError: name 'np' is not defined

## Array compatibility

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility shapes:", a.shape == b.shape)

Compatibility shapes: False


In [9]:
a = np.array([[1,2,3,31],
              [4,5,6,61],
              [7,8,9,10]])

print(a.shape)

(3, 4)


In [16]:
old_array = np.array([[1,2],
                      [3,4]])
new_row = np.array([5,6])
with_newRow = np.vstack((old_array,new_row))
print("Add row:",with_newRow)

new_column = np.array([[22],[23]])
with_newColumn = np.hstack((old_array,new_column))
print("Add column:",with_newColumn)


Add row: [[1 2]
 [3 4]
 [5 6]]
Add column: [[ 1  2 22]
 [ 3  4 23]]


In [17]:
arr = np.array([11,12,13,14,15])
deleted = np.delete(arr,2)
print(deleted)

[11 12 14 15]
